/**
 * Auto-generated TypeScript types with @pinta365/openapi-typegen
 * Generated at: 2026-02-06T21:17:29.993Z
 * Source file: https://cloud.ouraring.com/v2/static/json/openapi-1.28.json
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * Object defining activity score contributors.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 */
export interface ActivityContributors {
    /** Contribution of meeting previous 7-day daily activity targets in range [1, 100]. */
    meet_daily_targets?: number | null;
    /** Contribution of previous 24-hour inactivity alerts in range [1, 100]. */
    move_every_hour?: number | null;
    /** Contribution of previous 7-day recovery time in range [1, 100]. */
    recovery_time?: number | null;
    /** Contribution of previous 24-hour activity in range [1, 100]. */
    stay_active?: number | null;
    /** Contribution of previous 7-day exercise frequency in range [1, 100]. */
    training_frequency?: number | null;
    /** Contribution of previous 7-day exercise volume in range [1, 100]. */
    training_volume?: number | null;
}

/**
 * CreateWebhookSubscriptionRequest
 *
 * Used by:
 *  - POST /v2/webhook/subscription
 */
export interface CreateWebhookSubscriptionRequest {
    /** Callback Url */
    callback_url: string;
    /** Verification Token */
    verification_token: string;
    /** WebhookOperation */
    event_type: WebhookOperation;
    /** ExtApiV2DataType */
    data_type: ExtApiV2DataType;
}

/**
 * DailyActivityModel
 *
 * Used by:
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 */
export interface DailyActivityModel {
    /** Id */
    id: string;
    /**
     * 5-minute activity classification for the activity period:
     * * ```0```	non wear
     * * ```1``` rest
     * * ```2``` inactive
     * * ```3``` low activity
     * * ```4``` medium activity
     * * ```5``` high activity
     */
    class_5_min: string | null;
    /** Activity score in range ```[1, 100]``` */
    score: number | null;
    /** Active calories expended (in kilocalories) */
    active_calories: number;
    /** Average metabolic equivalent (MET) in minutes */
    average_met_minutes: number;
    /** Object defining activity score contributors. */
    contributors: ActivityContributors;
    /** Equivalent walking distance (in meters) of energy expenditure */
    equivalent_walking_distance: number;
    /** High activity metabolic equivalent (MET) in minutes */
    high_activity_met_minutes: number;
    /** High activity metabolic equivalent (MET) in seconds */
    high_activity_time: number;
    /** Number of inactivity alerts received */
    inactivity_alerts: number;
    /** Low activity metabolic equivalent (MET) in minutes */
    low_activity_met_minutes: number;
    /** Low activity metabolic equivalent (MET) in seconds */
    low_activity_time: number;
    /** Medium activity metabolic equivalent (MET) in minutes */
    medium_activity_met_minutes: number;
    /** Medium activity metabolic equivalent (MET) in seconds */
    medium_activity_time: number;
    /** SampleModel */
    met: SampleModel;
    /** Remaining meters to target (from ```target_meters``` */
    meters_to_target: number;
    /** The time (in seconds) in which the ring was not worn */
    non_wear_time: number;
    /** Resting time (in seconds) */
    resting_time: number;
    /** Sedentary metabolic equivalent (MET) in minutes */
    sedentary_met_minutes: number;
    /** Sedentary metabolic equivalent (MET) in seconds */
    sedentary_time: number;
    /** Total number of steps taken */
    steps: number;
    /** Daily activity target (in kilocalories) */
    target_calories: number;
    /** Daily activity target (in meters) */
    target_meters: number;
    /** Total calories expended (in kilocalories) */
    total_calories: number;
    /**
     * The ```YYYY-MM-DD``` formatted local date indicating when the daily activity occurred
     *
     * Format: date
     */
    day: string;
    /** ISO 8601 formatted local timestamp indicating the start datetime of when the daily activity occurred */
    timestamp: LocalDateTime;
}

/**
 * DailyCardiovascularAgeModel
 *
 * Used by:
 *  - GET /v2/usercollection/daily_cardiovascular_age
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age
 *  - GET /v2/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age/{document_id}
 */
export interface DailyCardiovascularAgeModel {
    /**
     * Day
     *
     * Format: date
     */
    day: string;
    /** 'Predicted vascular age in range [18, 100]. */
    vascular_age: number | null;
}

/**
 * DailyReadinessModel
 *
 * Used by:
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/daily_readiness/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_readiness/{document_id}
 */
export interface DailyReadinessModel {
    /** Id */
    id: string;
    /** Contributors of the daily readiness score. */
    contributors: ReadinessContributors;
    /**
     * Day that the daily readiness belongs to.
     *
     * Format: date
     */
    day: string;
    /** Daily readiness score. */
    score: number | null;
    /** Temperature deviation in degrees Celsius. */
    temperature_deviation: number | null;
    /** Temperature trend deviation in degrees Celsius. */
    temperature_trend_deviation: number | null;
    /** Timestamp of the daily readiness. */
    timestamp: LocalDateTime;
}

/**
 * DailyResilienceModel
 *
 * Used by:
 *  - GET /v2/usercollection/daily_resilience
 *  - GET /v2/sandbox/usercollection/daily_resilience
 *  - GET /v2/usercollection/daily_resilience/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_resilience/{document_id}
 */
export interface DailyResilienceModel {
    /** Id */
    id: string;
    /**
     * Day when the resilience record was recorded.
     *
     * Format: date
     */
    day: string;
    /** Contributors to the resilience score. */
    contributors: ResilienceContributors;
    /** Resilience level. */
    level: LongTermResilienceLevel;
}

/**
 * Object defining daily sleep.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_sleep/{document_id}
 */
export interface DailySleepModel {
    /** Id */
    id: string;
    /** Contributors for the daily sleep score. */
    contributors: SleepContributors;
    /**
     * Day that the daily sleep belongs to.
     *
     * Format: date
     */
    day: string;
    /** Daily sleep score. */
    score: number | null;
    /** Timestamp of the daily sleep. */
    timestamp: LocalDateTime;
}

/**
 * DailySpO2AggregatedValuesModel
 *
 * Used by:
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 *  - GET /v2/usercollection/daily_spo2/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_spo2/{document_id}
 */
export interface DailySpO2AggregatedValuesModel {
    /** Average oxygen saturation (SpO2) throughout the night. */
    average: number;
}

/**
 * DailySpO2Model
 *
 * Used by:
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 *  - GET /v2/usercollection/daily_spo2/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_spo2/{document_id}
 */
export interface DailySpO2Model {
    /** Id */
    id: string;
    /**
     * Day
     *
     * Format: date
     */
    day: string;
    /** The SpO2 percentage value aggregated over a single day. */
    spo2_percentage: DailySpO2AggregatedValuesModel | null;
    /** Breathing Disturbance Index (BDI) calculated using detected SpO2 drops from timeseries. Values should be in range [0, 100] */
    breathing_disturbance_index: number | null;
}

/**
 * Object defining daily stress.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 *  - GET /v2/usercollection/daily_stress/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_stress/{document_id}
 */
export interface DailyStressModel {
    /** Id */
    id: string;
    /**
     * Day that the daily stress belongs to.
     *
     * Format: date
     */
    day: string;
    /** Time (in seconds) spent in a high stress zone (top quartile data) */
    stress_high: number | null;
    /** Time (in seconds) spent in a high recovery zone (bottom quartile data) */
    recovery_high: number | null;
    /** Stress summary of full day. */
    day_summary?: DailyStressSummary | null;
}

/**
 * Possible daily stress summary types.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 *  - GET /v2/usercollection/daily_stress/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_stress/{document_id}
 */
export type DailyStressSummary = "restored" | "normal" | "stressful";

/**
 * An EnhancedTagModel maps an ASSATag. An ASSATag in ExtAPIV2 is called a EnhancedTag
 * An EnhancedTagModel will be populated by data from an ASSATag
 * The fields in the EnhancedTagModel map to fields in an ASSATag
 *
 * Used by:
 *  - GET /v2/usercollection/enhanced_tag
 *  - GET /v2/sandbox/usercollection/enhanced_tag
 *  - GET /v2/usercollection/enhanced_tag/{document_id}
 *  - GET /v2/sandbox/usercollection/enhanced_tag/{document_id}
 */
export interface EnhancedTagModel {
    /** Id */
    id: string;
    /** The unique code of the selected tag type, `NULL` for text-only tags, or `custom` for custom tag types. */
    tag_type_code?: string | null;
    /** Timestamp of the tag (if no duration) or the start time of the tag (with duration). */
    start_time: LocalDateTime;
    /** Timestamp of the tag's end for events with duration or `NULL` if there is no duration. */
    end_time?: LocalDateTime | null;
    /**
     * Day of the tag (if no duration) or the start day of the tag (with duration).
     *
     * Format: date
     */
    start_day: string;
    /** Day of the tag's end for events with duration or `NULL` if there is no duration. */
    end_day?: string | null;
    /** Additional freeform text on the tag. */
    comment?: string | null;
    /** The name of the tag if the tag_type_code is `custom`. */
    custom_name?: string | null;
}

/**
 * ExtApiV2DataType
 *
 * Used by:
 *  - GET /v2/webhook/subscription
 *  - POST /v2/webhook/subscription
 *  - GET /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/renew/{id}
 */
export type ExtApiV2DataType =
    | "tag"
    | "enhanced_tag"
    | "workout"
    | "session"
    | "sleep"
    | "daily_sleep"
    | "daily_readiness"
    | "daily_activity"
    | "daily_spo2"
    | "sleep_time"
    | "rest_mode_period"
    | "ring_configuration"
    | "daily_stress"
    | "daily_cardiovascular_age"
    | "daily_resilience"
    | "vo2_max";

/**
 * HTTPValidationError
 *
 * Used by:
 *  - GET /v2/usercollection/tag
 *  - GET /v2/sandbox/usercollection/tag
 *  - GET /v2/usercollection/enhanced_tag
 *  - GET /v2/sandbox/usercollection/enhanced_tag
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 *  - GET /v2/usercollection/daily_resilience
 *  - GET /v2/sandbox/usercollection/daily_resilience
 *  - GET /v2/usercollection/daily_cardiovascular_age
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 *  - GET /v2/usercollection/tag/{document_id}
 *  - GET /v2/sandbox/usercollection/tag/{document_id}
 *  - GET /v2/usercollection/enhanced_tag/{document_id}
 *  - GET /v2/sandbox/usercollection/enhanced_tag/{document_id}
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 *  - GET /v2/usercollection/daily_sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_sleep/{document_id}
 *  - GET /v2/usercollection/daily_spo2/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_spo2/{document_id}
 *  - GET /v2/usercollection/daily_readiness/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_readiness/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 *  - GET /v2/usercollection/daily_stress/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_stress/{document_id}
 *  - GET /v2/usercollection/daily_resilience/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_resilience/{document_id}
 *  - GET /v2/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/usercollection/vO2_max/{document_id}
 *  - GET /v2/sandbox/usercollection/vO2_max/{document_id}
 *  - POST /v2/webhook/subscription
 *  - GET /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/{id}
 *  - DELETE /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/renew/{id}
 *  - GET /v2/usercollection/heartrate
 *  - GET /v2/sandbox/usercollection/heartrate
 */
export interface HTTPValidationError {
    /** Detail */
    detail?: ValidationError[];
}

/**
 * HeartRateModel
 *
 * Used by:
 *  - GET /v2/usercollection/heartrate
 *  - GET /v2/sandbox/usercollection/heartrate
 */
export interface HeartRateModel {
    /** Bpm */
    bpm: number;
    /** HeartRateSource */
    source: HeartRateSource;
    /** LocalDateTime */
    timestamp: LocalDateTime;
}

/**
 * HeartRateSource
 *
 * Used by:
 *  - GET /v2/usercollection/heartrate
 *  - GET /v2/sandbox/usercollection/heartrate
 */
export type HeartRateSource = "awake" | "rest" | "sleep" | "session" | "live" | "workout";

/**
 * ISODate
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 */
export type ISODate = string;

/**
 * LocalDateTime
 *
 * Used by:
 *  - GET /v2/usercollection/tag
 *  - GET /v2/sandbox/usercollection/tag
 *  - GET /v2/usercollection/enhanced_tag
 *  - GET /v2/sandbox/usercollection/enhanced_tag
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 *  - GET /v2/usercollection/tag/{document_id}
 *  - GET /v2/sandbox/usercollection/tag/{document_id}
 *  - GET /v2/usercollection/enhanced_tag/{document_id}
 *  - GET /v2/sandbox/usercollection/enhanced_tag/{document_id}
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 *  - GET /v2/usercollection/daily_sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_sleep/{document_id}
 *  - GET /v2/usercollection/daily_readiness/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_readiness/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 *  - GET /v2/usercollection/vO2_max/{document_id}
 *  - GET /v2/sandbox/usercollection/vO2_max/{document_id}
 *  - GET /v2/usercollection/heartrate
 *  - GET /v2/sandbox/usercollection/heartrate
 */
export type LocalDateTime = string;

/**
 * LocalDateTimeWithMilliseconds
 *
 * Used by:
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export type LocalDateTimeWithMilliseconds = string;

/**
 * LocalizedDateTime
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 */
export type LocalizedDateTime = string;

/**
 * Possible long term resilience level values.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_resilience
 *  - GET /v2/sandbox/usercollection/daily_resilience
 *  - GET /v2/usercollection/daily_resilience/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_resilience/{document_id}
 */
export type LongTermResilienceLevel = "limited" | "adequate" | "solid" | "strong" | "exceptional";

/**
 * Possible Moment moods.
 *
 * Used by:
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 */
export type MomentMood = "bad" | "worse" | "same" | "good" | "great";

/**
 * Possible Moment types.
 *
 * Used by:
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 */
export type MomentType = "breathing" | "meditation" | "nap" | "relaxation" | "rest" | "body_status";

/**
 * MultiDocumentResponse[DailyActivityModel]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 */
export interface MultiDocumentResponseDailyActivityModel_ {
    /** Data */
    data: DailyActivityModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[DailyCardiovascularAgeModel]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_cardiovascular_age
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age
 */
export interface MultiDocumentResponseDailyCardiovascularAgeModel_ {
    /** Data */
    data: DailyCardiovascularAgeModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[DailyReadinessModel]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 */
export interface MultiDocumentResponseDailyReadinessModel_ {
    /** Data */
    data: DailyReadinessModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[DailyResilienceModel]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_resilience
 *  - GET /v2/sandbox/usercollection/daily_resilience
 */
export interface MultiDocumentResponseDailyResilienceModel_ {
    /** Data */
    data: DailyResilienceModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[DailySleepModel]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 */
export interface MultiDocumentResponseDailySleepModel_ {
    /** Data */
    data: DailySleepModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[DailySpO2Model]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 */
export interface MultiDocumentResponseDailySpO2Model_ {
    /** Data */
    data: DailySpO2Model[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[DailyStressModel]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 */
export interface MultiDocumentResponseDailyStressModel_ {
    /** Data */
    data: DailyStressModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[EnhancedTagModel]
 *
 * Used by:
 *  - GET /v2/usercollection/enhanced_tag
 *  - GET /v2/sandbox/usercollection/enhanced_tag
 */
export interface MultiDocumentResponseEnhancedTagModel_ {
    /** Data */
    data: EnhancedTagModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicWorkout]
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 */
export interface MultiDocumentResponsePublicWorkout_ {
    /** Data */
    data: PublicWorkout[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[RestModePeriodModel]
 *
 * Used by:
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 */
export interface MultiDocumentResponseRestModePeriodModel_ {
    /** Data */
    data: RestModePeriodModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[RingConfigurationModel]
 *
 * Used by:
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 */
export interface MultiDocumentResponseRingConfigurationModel_ {
    /** Data */
    data: RingConfigurationModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[SessionModel]
 *
 * Used by:
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 */
export interface MultiDocumentResponseSessionModel_ {
    /** Data */
    data: SessionModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[SleepModel]
 *
 * Used by:
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 */
export interface MultiDocumentResponseSleepModel_ {
    /** Data */
    data: SleepModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[SleepTimeModel]
 *
 * Used by:
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 */
export interface MultiDocumentResponseSleepTimeModel_ {
    /** Data */
    data: SleepTimeModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[TagModel]
 *
 * Used by:
 *  - GET /v2/usercollection/tag
 *  - GET /v2/sandbox/usercollection/tag
 */
export interface MultiDocumentResponseTagModel_ {
    /** Data */
    data: TagModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[VO2MaxModel]
 *
 * Used by:
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 */
export interface MultiDocumentResponseVO2MaxModel_ {
    /** Data */
    data: VO2MaxModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * PersonalInfoResponse
 *
 * Used by:
 *  - GET /v2/usercollection/personal_info
 */
export interface PersonalInfoResponse {
    /** Id */
    id: string;
    /** Age */
    age?: number | null;
    /** Weight */
    weight?: number | null;
    /** Height */
    height?: number | null;
    /** Biological Sex */
    biological_sex?: string | null;
    /** Email */
    email?: string | null;
}

/**
 * Public model for Workout.
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 */
export interface PublicWorkout {
    /** Unique identifier of the object. */
    id: string;
    /** Type of the workout activity. */
    activity: string;
    /** Energy burned in kilocalories during the workout. */
    calories?: number | null;
    /** Day when the workout occurred. */
    day: ISODate;
    /** Distance traveled in meters during the workout. */
    distance?: number | null;
    /** Timestamp indicating when the workout ended. */
    end_datetime: LocalizedDateTime;
    /** Intensity of the workout. */
    intensity: PublicWorkoutIntensity;
    /** User-defined label for the workout. */
    label?: string | null;
    /** Possible workout sources. */
    source: PublicWorkoutSource;
    /** Timestamp indicating when the workout started. */
    start_datetime: LocalizedDateTime;
}

/**
 * Possible workout intensities.
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 */
export type PublicWorkoutIntensity = "easy" | "moderate" | "hard";

/**
 * Possible workout sources.
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 */
export type PublicWorkoutSource = "manual" | "autodetected" | "confirmed" | "workout_heart_rate";

/**
 * Object defining readiness score contributors.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/daily_readiness/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_readiness/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export interface ReadinessContributors {
    /** Contribution of cumulative activity balance in range [1, 100]. */
    activity_balance: number | null;
    /** Contribution of body temperature in range [1, 100]. */
    body_temperature: number | null;
    /** Contribution of heart rate variability balance in range [1, 100]. */
    hrv_balance: number | null;
    /** Contribution of previous day's activity in range [1, 100]. */
    previous_day_activity: number | null;
    /** Contribution of previous night's sleep in range [1, 100]. */
    previous_night: number | null;
    /** Contribution of recovery index in range [1, 100]. */
    recovery_index: number | null;
    /** Contribution of resting heart rate in range [1, 100]. */
    resting_heart_rate: number | null;
    /** Contribution of sleep balance in range [1, 100]. */
    sleep_balance: number | null;
    /** Contribution of sleep regularity in range [1, 100]. */
    sleep_regularity: number | null;
}

/**
 * ReadinessSummary
 *
 * Used by:
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export interface ReadinessSummary {
    /** Object defining readiness score contributors. */
    contributors: ReadinessContributors;
    /** Score */
    score?: number | null;
    /** Temperature Deviation */
    temperature_deviation?: number | null;
    /** Temperature Trend Deviation */
    temperature_trend_deviation?: number | null;
}

/**
 * ResilienceContributors
 *
 * Used by:
 *  - GET /v2/usercollection/daily_resilience
 *  - GET /v2/sandbox/usercollection/daily_resilience
 *  - GET /v2/usercollection/daily_resilience/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_resilience/{document_id}
 */
export interface ResilienceContributors {
    /** Sleep recovery contributor to the resilience score. Range: [0, 100] */
    sleep_recovery: number;
    /** Daytime recovery contributor to the resilience score. Range: [0, 100] */
    daytime_recovery: number;
    /** Stress contributor to the resilience score. Range: [0, 100] */
    stress: number;
}

/**
 * Object defining a Rest Mode episode.
 *
 * Used by:
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 */
export interface RestModeEpisode {
    /** Tags selected for the episode. */
    tags: string[];
    /** Timestamp indicating when the episode occurred. */
    timestamp: LocalizedDateTime;
}

/**
 * Object contains information about rest mode episode.
 *
 * Used by:
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 */
export interface RestModePeriodModel {
    /** Id */
    id: string;
    /** End date of rest mode. */
    end_day?: string | null;
    /** Timestamp when rest mode ended. */
    end_time?: LocalDateTime | null;
    /** Collection of episodes during rest mode, consisting of tags. */
    episodes: RestModeEpisode[];
    /**
     * Start date of rest mode.
     *
     * Format: date
     */
    start_day: string;
    /** Timestamp when rest mode started. */
    start_time: LocalDateTime | null;
}

/**
 * RingColor
 *
 * Used by:
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 */
export type RingColor =
    | "brushed_silver"
    | "glossy_black"
    | "glossy_gold"
    | "glossy_white"
    | "gucci"
    | "matt_gold"
    | "rose"
    | "silver"
    | "stealth_black"
    | "titanium"
    | "titanium_and_gold";

/**
 * RingConfigurationModel
 *
 * Used by:
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 */
export interface RingConfigurationModel {
    /** Id */
    id: string;
    /** Color of the ring. */
    color?: RingColor | null;
    /** Design of the ring. */
    design?: RingDesign | null;
    /** Firmware version of the ring. */
    firmware_version?: string | null;
    /** Hardware type of the ring. */
    hardware_type?: RingHardwareType | null;
    /** UTC timestamp indicating when the ring was set up. */
    set_up_at?: LocalDateTime | null;
    /** US size of the ring. */
    size?: number | null;
}

/**
 * RingDesign
 *
 * Used by:
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 */
export type RingDesign = "balance" | "balance_diamond" | "heritage" | "horizon";

/**
 * RingHardwareType
 *
 * Used by:
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 */
export type RingHardwareType = "gen1" | "gen2" | "gen2m" | "gen3" | "gen4";

/**
 * SampleModel
 *
 * Used by:
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export interface SampleModel {
    /** Interval in seconds between the sampled items. */
    interval: number;
    /** Recorded sample items. */
    items: number | null[];
    /** Timestamp when the sample recording started. */
    timestamp: LocalDateTimeWithMilliseconds;
}

/**
 * SessionModel
 *
 * Used by:
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 */
export interface SessionModel {
    /** Id */
    id: string;
    /**
     * The date when the session occurred.
     *
     * Format: date
     */
    day: string;
    /** Timestamp indicating when the Moment ended. */
    start_datetime: LocalDateTime;
    /** Timestamp indicating when the Moment ended. */
    end_datetime: LocalDateTime;
    /** Possible Moment types. */
    type: MomentType;
    heart_rate?: SampleModel | null;
    heart_rate_variability?: SampleModel | null;
    mood?: MomentMood | null;
    motion_count?: SampleModel | null;
}

/**
 * SleepAlgorithmVersion
 *
 * Used by:
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export type SleepAlgorithmVersion = "v1" | "v2";

/**
 * Possible sleep analysis reasons.
 *
 * Used by:
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export type SleepAnalysisReason = "foreground_sleep_analysis" | "bedtime_edit";

/**
 * Object defining sleep score contributors.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_sleep/{document_id}
 */
export interface SleepContributors {
    /** Contribution of deep sleep in range [1, 100]. */
    deep_sleep?: number | null;
    /** Contribution of sleep efficiency in range [1, 100]. */
    efficiency?: number | null;
    /** Contribution of sleep latency in range [1, 100]. */
    latency?: number | null;
    /** Contribution of REM sleep in range [1, 100]. */
    rem_sleep?: number | null;
    /** Contribution of sleep restfulness in range [1, 100]. */
    restfulness?: number | null;
    /** Contribution of sleep timing in range [1, 100]. */
    timing?: number | null;
    /** Contribution of total sleep in range [1, 100]. */
    total_sleep?: number | null;
}

/**
 * SleepModel
 *
 * Used by:
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export interface SleepModel {
    /** Id */
    id: string;
    /** Average breathing rate during sleep as breaths/second. */
    average_breath: number | null;
    /** Average heart rate during sleep as beats/minute. */
    average_heart_rate: number | null;
    /** Average heart rate variability during sleep. */
    average_hrv: number | null;
    /** Duration spent awake in seconds. */
    awake_time: number | null;
    /** Bedtime end of the sleep. */
    bedtime_end: LocalDateTime;
    /** Bedtime start of the sleep. */
    bedtime_start: LocalDateTime;
    /**
     * Day that the sleep belongs to.
     *
     * Format: date
     */
    day: string;
    /** Duration spent in deep sleep in seconds. */
    deep_sleep_duration: number | null;
    /** Sleep efficiency rating in range [1, 100]. */
    efficiency: number | null;
    /** Object containing heart rate samples. */
    heart_rate: SampleModel | null;
    hrv: SampleModel | null;
    /** Sleep latency in seconds. This is the time it took for the user to fall asleep after going to bed. */
    latency: number | null;
    /** Duration spent in light sleep in seconds. */
    light_sleep_duration: number | null;
    /** Flag indicating if a low battery alert occurred. */
    low_battery_alert: boolean;
    /** Lowest heart rate during sleep. */
    lowest_heart_rate: number | null;
    /**
     *         30-second movement classification for the period where every character corresponds to:
     *         '1' = no motion,
     *         '2' = restless,
     *         '3' = tossing and turning
     *         '4' = active
     */
    movement_30_sec: string | null;
    /** ECore sleep period identifier. */
    period: number;
    /** Object containing the readiness details for this sleep. As opposed to the daily readiness object which represents the readiness for the entire day. */
    readiness: ReadinessSummary | null;
    /** Effect on readiness score caused by this sleep period. */
    readiness_score_delta: number | null;
    /** Duration spent in REM sleep in seconds. */
    rem_sleep_duration: number | null;
    /** Number of restless periods during sleep. */
    restless_periods: number | null;
    /**
     *         5-minute sleep phase classification for the period where every character corresponds to:
     *         '1' = deep sleep,
     *         '2' = light sleep,
     *         '3' = REM sleep
     *         '4' = awake.
     */
    sleep_phase_5_min: string | null;
    /** Effect on sleep score caused by this sleep period. */
    sleep_score_delta: number | null;
    /** Version of the sleep algorithm used to calculate the sleep data. */
    sleep_algorithm_version: SleepAlgorithmVersion | null;
    /** The reason for the creation or update of the latest version of this sleep. */
    sleep_analysis_reason?: SleepAnalysisReason | null;
    /** Duration spent in bed in seconds. */
    time_in_bed: number;
    /** Total sleep duration in seconds. */
    total_sleep_duration: number | null;
    /**
     * Possible sleep period types.
     * 'deleted' = deleted sleep by user.
     * 'sleep' = user confirmed sleep / nap, min 15 minutes, max 3 hours, contributes to daily scores
     * 'late_nap' = user confirmed sleep / nap, min 15 minutes, ended after sleep day change (6 pm), contributes to next days daily scores
     * 'long_sleep' = sleep that is long enough (>3h) to automatically contribute to daily scores
     * 'rest' = Falsely detected sleep / nap, rejected in confirm prompt by user
     */
    type: SleepType;
}

/**
 * Object contains suggested bedtime for the user.
 *
 * Used by:
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 */
export interface SleepTimeModel {
    /** Id */
    id: string;
    /**
     * Corresponding day for the sleep time.
     *
     * Format: date
     */
    day: string;
    /** Optimal bedtime. */
    optimal_bedtime?: SleepTimeWindow | null;
    /** Recommended action for bedtime. */
    recommendation?: SleepTimeRecommendation | null;
    /** Sleep time status; used to inform sleep time recommendation. */
    status?: SleepTimeStatus | null;
}

/**
 * Possible SleepTime recommendation.
 *
 * Used by:
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 */
export type SleepTimeRecommendation =
    | "improve_efficiency"
    | "earlier_bedtime"
    | "later_bedtime"
    | "earlier_wake_up_time"
    | "later_wake_up_time"
    | "follow_optimal_bedtime";

/**
 * Possible SleepTime status.
 *
 * Used by:
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 */
export type SleepTimeStatus =
    | "not_enough_nights"
    | "not_enough_recent_nights"
    | "bad_sleep_quality"
    | "only_recommended_found"
    | "optimal_found";

/**
 * Object defining sleep time window
 *
 * Used by:
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 */
export interface SleepTimeWindow {
    /** Timezone offset in second from GMT of the day */
    day_tz: number;
    /** End offset from midnight in second */
    end_offset: number;
    /** Start offset from midnight in second */
    start_offset: number;
}

/**
 * Possible sleep period types.
 * 'deleted' = deleted sleep by user.
 * 'sleep' = user confirmed sleep / nap, min 15 minutes, max 3 hours, contributes to daily scores
 * 'late_nap' = user confirmed sleep / nap, min 15 minutes, ended after sleep day change (6 pm), contributes to next days daily scores
 * 'long_sleep' = sleep that is long enough (>3h) to automatically contribute to daily scores
 * 'rest' = Falsely detected sleep / nap, rejected in confirm prompt by user
 *
 * Used by:
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export type SleepType = "deleted" | "sleep" | "long_sleep" | "late_nap" | "rest";

/**
 * A TagModel maps to an ASSANote. An ASSANote in ExtAPIV2 is called a Tag
 * A TagModel will be populated by data from an ASSANote
 * The fields in the TagModel map to fields in an ASSANote
 *
 * Used by:
 *  - GET /v2/usercollection/tag
 *  - GET /v2/sandbox/usercollection/tag
 *  - GET /v2/usercollection/tag/{document_id}
 *  - GET /v2/sandbox/usercollection/tag/{document_id}
 */
export interface TagModel {
    /** Id */
    id: string;
    /**
     * Day that the note belongs to.
     *
     * Format: date
     */
    day: string;
    /** Textual contents of the note. */
    text: string | null;
    /** Timestamp of the note. */
    timestamp: LocalDateTime;
    /** Selected tags for the tag. */
    tags: string[];
}

/**
 * TimeSeriesResponse[HeartRateModel]
 *
 * Used by:
 *  - GET /v2/usercollection/heartrate
 *  - GET /v2/sandbox/usercollection/heartrate
 */
export interface TimeSeriesResponseHeartRateModel_ {
    /** Data */
    data: HeartRateModel[];
    /** Next Token */
    next_token?: string | null;
}

/**
 * UpdateWebhookSubscriptionRequest
 *
 * Used by:
 *  - PUT /v2/webhook/subscription/{id}
 */
export interface UpdateWebhookSubscriptionRequest {
    /** Verification Token */
    verification_token: string;
    /** Callback Url */
    callback_url?: string | null;
    event_type?: WebhookOperation | null;
    data_type?: ExtApiV2DataType | null;
}

/** UtcDateTime */
export type UtcDateTime = string;

/**
 * VO2MaxModel
 *
 * Used by:
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 *  - GET /v2/usercollection/vO2_max/{document_id}
 *  - GET /v2/sandbox/usercollection/vO2_max/{document_id}
 */
export interface VO2MaxModel {
    /** Id */
    id: string;
    /**
     * Day that the estimate belongs to.
     *
     * Format: date
     */
    day: string;
    /** Timestamp indicating when the estimate was created. */
    timestamp: LocalDateTime;
    /** VO2 max value. */
    vo2_max: number | null;
}

/**
 * ValidationError
 *
 * Used by:
 *  - GET /v2/usercollection/tag
 *  - GET /v2/sandbox/usercollection/tag
 *  - GET /v2/usercollection/enhanced_tag
 *  - GET /v2/sandbox/usercollection/enhanced_tag
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 *  - GET /v2/usercollection/daily_resilience
 *  - GET /v2/sandbox/usercollection/daily_resilience
 *  - GET /v2/usercollection/daily_cardiovascular_age
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 *  - GET /v2/usercollection/tag/{document_id}
 *  - GET /v2/sandbox/usercollection/tag/{document_id}
 *  - GET /v2/usercollection/enhanced_tag/{document_id}
 *  - GET /v2/sandbox/usercollection/enhanced_tag/{document_id}
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 *  - GET /v2/usercollection/daily_sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_sleep/{document_id}
 *  - GET /v2/usercollection/daily_spo2/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_spo2/{document_id}
 *  - GET /v2/usercollection/daily_readiness/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_readiness/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 *  - GET /v2/usercollection/daily_stress/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_stress/{document_id}
 *  - GET /v2/usercollection/daily_resilience/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_resilience/{document_id}
 *  - GET /v2/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/usercollection/vO2_max/{document_id}
 *  - GET /v2/sandbox/usercollection/vO2_max/{document_id}
 *  - POST /v2/webhook/subscription
 *  - GET /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/{id}
 *  - DELETE /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/renew/{id}
 *  - GET /v2/usercollection/heartrate
 *  - GET /v2/sandbox/usercollection/heartrate
 */
export interface ValidationError {
    /** Location */
    loc: string | number[];
    /** Message */
    msg: string;
    /** Error Type */
    type: string;
}

/**
 * WebhookOperation
 *
 * Used by:
 *  - GET /v2/webhook/subscription
 *  - POST /v2/webhook/subscription
 *  - GET /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/renew/{id}
 */
export type WebhookOperation = "create" | "update" | "delete";

/**
 * WebhookSubscriptionModel
 *
 * Used by:
 *  - GET /v2/webhook/subscription
 *  - POST /v2/webhook/subscription
 *  - GET /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/renew/{id}
 */
export interface WebhookSubscriptionModel {
    /**
     * Id
     *
     * Format: uuid4
     */
    id: string;
    /** Callback Url */
    callback_url: string;
    /** WebhookOperation */
    event_type: WebhookOperation;
    /** ExtApiV2DataType */
    data_type: ExtApiV2DataType;
    /**
     * Expiration Time
     *
     * Format: date-time
     */
    expiration_time: string;
}
