/**
 * Auto-generated TypeScript types with @pinta365/openapi-typegen
 * Generated at: 2026-05-04T19:26:15.241Z
 * Source file: https://cloud.ouraring.com/v2/static/json/openapi-1.29.json
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * ArrayNullableFloatBits64
 *
 * Used by:
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export type ArrayUnionFloat_NoneType_Bits64_ = number | null[];

/**
 * CreateWebhookSubscriptionRequest
 *
 * Used by:
 *  - POST /v2/webhook/subscription
 */
export interface CreateWebhookSubscriptionRequest {
    /** Callback Url */
    callback_url: string;
    /** Verification Token */
    verification_token: string;
    /** WebhookOperation */
    event_type: WebhookOperation;
    /** ExtApiV2DataType */
    data_type: ExtApiV2DataType;
}

/**
 * DailyResilienceModel
 *
 * Used by:
 *  - GET /v2/usercollection/daily_resilience
 *  - GET /v2/sandbox/usercollection/daily_resilience
 *  - GET /v2/usercollection/daily_resilience/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_resilience/{document_id}
 */
export interface DailyResilienceModel {
    /** Id */
    id: string;
    /**
     * Day when the resilience record was recorded.
     *
     * Format: date
     */
    day: string;
    /** Contributors to the resilience score. */
    contributors: ResilienceContributors;
    /** Resilience level. */
    level: LongTermResilienceLevel;
}

/**
 * An EnhancedTagModel maps an ASSATag. An ASSATag in ExtAPIV2 is called a EnhancedTag
 * An EnhancedTagModel will be populated by data from an ASSATag
 * The fields in the EnhancedTagModel map to fields in an ASSATag
 *
 * Used by:
 *  - GET /v2/usercollection/enhanced_tag
 *  - GET /v2/sandbox/usercollection/enhanced_tag
 *  - GET /v2/usercollection/enhanced_tag/{document_id}
 *  - GET /v2/sandbox/usercollection/enhanced_tag/{document_id}
 */
export interface EnhancedTagModel {
    /** Id */
    id: string;
    /** The unique code of the selected tag type, `NULL` for text-only tags, or `custom` for custom tag types. */
    tag_type_code?: string | null;
    /** Timestamp of the tag (if no duration) or the start time of the tag (with duration). */
    start_time: LocalDateTime;
    /** Timestamp of the tag's end for events with duration or `NULL` if there is no duration. */
    end_time?: LocalDateTime | null;
    /**
     * Day of the tag (if no duration) or the start day of the tag (with duration).
     *
     * Format: date
     */
    start_day: string;
    /** Day of the tag's end for events with duration or `NULL` if there is no duration. */
    end_day?: string | null;
    /** Additional freeform text on the tag. */
    comment?: string | null;
    /** The name of the tag if the tag_type_code is `custom`. */
    custom_name?: string | null;
}

/**
 * ExtApiV2DataType
 *
 * Used by:
 *  - GET /v2/webhook/subscription
 *  - POST /v2/webhook/subscription
 *  - GET /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/renew/{id}
 */
export type ExtApiV2DataType =
    | "tag"
    | "enhanced_tag"
    | "workout"
    | "session"
    | "sleep"
    | "daily_sleep"
    | "daily_readiness"
    | "daily_activity"
    | "daily_spo2"
    | "sleep_time"
    | "rest_mode_period"
    | "ring_configuration"
    | "daily_stress"
    | "daily_cycle_phases"
    | "activation_status"
    | "daily_cardiovascular_age"
    | "daily_resilience"
    | "vo2_max"
    | "period_start"
    | "pregnancy"
    | "fertile_window"
    | "ovulation_confirmed"
    | "blood_glucose";

/**
 * HTTPValidationError
 *
 * Used by:
 *  - GET /v2/usercollection/tag
 *  - GET /v2/sandbox/usercollection/tag
 *  - GET /v2/usercollection/enhanced_tag
 *  - GET /v2/sandbox/usercollection/enhanced_tag
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 *  - GET /v2/usercollection/daily_resilience
 *  - GET /v2/sandbox/usercollection/daily_resilience
 *  - GET /v2/usercollection/daily_cardiovascular_age
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 *  - GET /v2/usercollection/tag/{document_id}
 *  - GET /v2/sandbox/usercollection/tag/{document_id}
 *  - GET /v2/usercollection/enhanced_tag/{document_id}
 *  - GET /v2/sandbox/usercollection/enhanced_tag/{document_id}
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 *  - GET /v2/usercollection/daily_sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_sleep/{document_id}
 *  - GET /v2/usercollection/daily_spo2/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_spo2/{document_id}
 *  - GET /v2/usercollection/daily_readiness/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_readiness/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 *  - GET /v2/usercollection/daily_stress/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_stress/{document_id}
 *  - GET /v2/usercollection/daily_resilience/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_resilience/{document_id}
 *  - GET /v2/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/usercollection/vO2_max/{document_id}
 *  - GET /v2/sandbox/usercollection/vO2_max/{document_id}
 *  - POST /v2/webhook/subscription
 *  - GET /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/{id}
 *  - DELETE /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/renew/{id}
 *  - GET /v2/usercollection/heartrate
 *  - GET /v2/sandbox/usercollection/heartrate
 *  - GET /v2/usercollection/ring_battery_level
 *  - GET /v2/sandbox/usercollection/ring_battery_level
 *  - GET /v2/usercollection/interbeat_interval
 *  - GET /v2/sandbox/usercollection/interbeat_interval
 */
export interface HTTPValidationError {
    /** Detail */
    detail?: ValidationError[];
}

/**
 * ISODate
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 *  - GET /v2/usercollection/daily_cardiovascular_age
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 *  - GET /v2/usercollection/daily_sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_sleep/{document_id}
 *  - GET /v2/usercollection/daily_spo2/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_spo2/{document_id}
 *  - GET /v2/usercollection/daily_readiness/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_readiness/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/usercollection/daily_stress/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_stress/{document_id}
 *  - GET /v2/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/usercollection/vO2_max/{document_id}
 *  - GET /v2/sandbox/usercollection/vO2_max/{document_id}
 */
export type ISODate = string;

/**
 * LocalDateTime
 *
 * Used by:
 *  - GET /v2/usercollection/tag
 *  - GET /v2/sandbox/usercollection/tag
 *  - GET /v2/usercollection/enhanced_tag
 *  - GET /v2/sandbox/usercollection/enhanced_tag
 *  - GET /v2/usercollection/tag/{document_id}
 *  - GET /v2/sandbox/usercollection/tag/{document_id}
 *  - GET /v2/usercollection/enhanced_tag/{document_id}
 *  - GET /v2/sandbox/usercollection/enhanced_tag/{document_id}
 */
export type LocalDateTime = string;

/**
 * LocalizedDateTime
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 *  - GET /v2/usercollection/daily_sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_sleep/{document_id}
 *  - GET /v2/usercollection/daily_readiness/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_readiness/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/usercollection/vO2_max/{document_id}
 *  - GET /v2/sandbox/usercollection/vO2_max/{document_id}
 */
export type LocalizedDateTime = string;

/**
 * Possible long term resilience level values.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_resilience
 *  - GET /v2/sandbox/usercollection/daily_resilience
 *  - GET /v2/usercollection/daily_resilience/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_resilience/{document_id}
 */
export type LongTermResilienceLevel = "limited" | "adequate" | "solid" | "strong" | "exceptional";

/**
 * Object defining the metadata of a collection model instance.
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 *  - GET /v2/usercollection/daily_cardiovascular_age
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 *  - GET /v2/usercollection/daily_sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_sleep/{document_id}
 *  - GET /v2/usercollection/daily_spo2/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_spo2/{document_id}
 *  - GET /v2/usercollection/daily_readiness/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_readiness/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 *  - GET /v2/usercollection/daily_stress/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_stress/{document_id}
 *  - GET /v2/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/usercollection/vO2_max/{document_id}
 *  - GET /v2/sandbox/usercollection/vO2_max/{document_id}
 */
export interface Metadata {
    /** Timestamp indicating when the object was last updated. */
    updated_at: UtcDateTime;
    /** Version number of the object. */
    version: number;
}

/**
 * MultiDocumentResponseDict
 *
 * Used by:
 *  - GET /v2/usercollection/tag
 *  - GET /v2/sandbox/usercollection/tag
 *  - GET /v2/usercollection/enhanced_tag
 *  - GET /v2/sandbox/usercollection/enhanced_tag
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 *  - GET /v2/usercollection/daily_resilience
 *  - GET /v2/sandbox/usercollection/daily_resilience
 *  - GET /v2/usercollection/daily_cardiovascular_age
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 */
export interface MultiDocumentResponseDict {
    /** Data */
    data: object[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[DailyResilienceModel]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_resilience
 *  - GET /v2/sandbox/usercollection/daily_resilience
 */
export interface MultiDocumentResponseDailyResilienceModel_ {
    /** Data */
    data: DailyResilienceModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[EnhancedTagModel]
 *
 * Used by:
 *  - GET /v2/usercollection/enhanced_tag
 *  - GET /v2/sandbox/usercollection/enhanced_tag
 */
export interface MultiDocumentResponseEnhancedTagModel_ {
    /** Data */
    data: EnhancedTagModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicDailyActivity]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 */
export interface MultiDocumentResponsePublicDailyActivity_ {
    /** Data */
    data: PublicDailyActivity[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicDailyCardiovascularAge]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_cardiovascular_age
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age
 */
export interface MultiDocumentResponsePublicDailyCardiovascularAge_ {
    /** Data */
    data: PublicDailyCardiovascularAge[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicDailyReadiness]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 */
export interface MultiDocumentResponsePublicDailyReadiness_ {
    /** Data */
    data: PublicDailyReadiness[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicDailySleep]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 */
export interface MultiDocumentResponsePublicDailySleep_ {
    /** Data */
    data: PublicDailySleep[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicDailySpO2]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 */
export interface MultiDocumentResponsePublicDailySpO2_ {
    /** Data */
    data: PublicDailySpO2[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicDailyStress]
 *
 * Used by:
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 */
export interface MultiDocumentResponsePublicDailyStress_ {
    /** Data */
    data: PublicDailyStress[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicModifiedSleepModel]
 *
 * Used by:
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 */
export interface MultiDocumentResponsePublicModifiedSleepModel_ {
    /** Data */
    data: PublicModifiedSleepModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicRestModePeriod]
 *
 * Used by:
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 */
export interface MultiDocumentResponsePublicRestModePeriod_ {
    /** Data */
    data: PublicRestModePeriod[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicRingConfiguration]
 *
 * Used by:
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 */
export interface MultiDocumentResponsePublicRingConfiguration_ {
    /** Data */
    data: PublicRingConfiguration[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicSession]
 *
 * Used by:
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 */
export interface MultiDocumentResponsePublicSession_ {
    /** Data */
    data: PublicSession[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicSleepTime]
 *
 * Used by:
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 */
export interface MultiDocumentResponsePublicSleepTime_ {
    /** Data */
    data: PublicSleepTime[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicVO2Max]
 *
 * Used by:
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 */
export interface MultiDocumentResponsePublicVO2Max_ {
    /** Data */
    data: PublicVO2Max[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[PublicWorkout]
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 */
export interface MultiDocumentResponsePublicWorkout_ {
    /** Data */
    data: PublicWorkout[];
    /** Next Token */
    next_token: string | null;
}

/**
 * MultiDocumentResponse[TagModel]
 *
 * Used by:
 *  - GET /v2/usercollection/tag
 *  - GET /v2/sandbox/usercollection/tag
 */
export interface MultiDocumentResponseTagModel_ {
    /** Data */
    data: TagModel[];
    /** Next Token */
    next_token: string | null;
}

/**
 * PersonalInfoResponse
 *
 * Used by:
 *  - GET /v2/usercollection/personal_info
 */
export interface PersonalInfoResponse {
    /** Id */
    id: string;
    /** Age */
    age?: number | null;
    /** Weight */
    weight?: number | null;
    /** Height */
    height?: number | null;
    /** Biological Sex */
    biological_sex?: string | null;
    /** Email */
    email?: string | null;
}

/**
 * Object defining activity score contributors.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 */
export interface PublicActivityContributors {
    /** Contribution of meeting previous 7-day daily activity targets in range [1, 100]. */
    meet_daily_targets?: number | null;
    /** Contribution of previous 24-hour inactivity alerts in range [1, 100]. */
    move_every_hour?: number | null;
    /** Contribution of previous 7-day recovery time in range [1, 100]. */
    recovery_time?: number | null;
    /** Contribution of previous 24-hour activity in range [1, 100]. */
    stay_active?: number | null;
    /** Contribution of previous 7-day exercise frequency in range [1, 100]. */
    training_frequency?: number | null;
    /** Contribution of previous 7-day exercise volume in range [1, 100]. */
    training_volume?: number | null;
}

/**
 * Object defining a daily activity that is a 24-hour period starting at 4 a.m.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 */
export interface PublicDailyActivity {
    /** Unique identifier of the object. */
    id: string;
    /** Meta data of the object. */
    meta: Metadata;
    /** Active calories expended in kilocalories. */
    active_calories: number;
    /** Average MET minutes. */
    average_met_minutes: number;
    /**
     * 5-minute activity classification for the period where every character corresponds to:
     * '0' = non wear
     * '1' = rest
     * '2' = inactive
     * '3' = low activity
     * '4' = medium activity
     * '5' = high activity
     * Example: "001233334555524001".
     */
    class_5_min?: string | null;
    /** Object containing activity score contributors. */
    contributors: PublicActivityContributors;
    /** Day that the daily activity belong to. */
    day: ISODate;
    /** Equivalent walking distance of energe expenditure in meters. */
    equivalent_walking_distance: number;
    /** The total METs of each minute classified as high activity. */
    high_activity_met_minutes: number;
    /** The total time in seconds of each minute classified as high activity. */
    high_activity_time: number;
    /** Number of inactivity alerts received. */
    inactivity_alerts: number;
    /** The total METs of each minute classified as low activity. */
    low_activity_met_minutes: number;
    /** The total time in seconds of each minute classified as low activity. */
    low_activity_time: number;
    /** The total METs of each minute classified as medium activity. */
    medium_activity_met_minutes: number;
    /** The total time in seconds of each minute classified as medium activity. */
    medium_activity_time: number;
    /** Sample containing METs. */
    met: PublicSample;
    /** Meters remaining to target. */
    meters_to_target: number;
    /** Ring non-wear time in seconds. */
    non_wear_time: number;
    /** Resting time in seconds. */
    resting_time: number;
    /** Activity score in range [1, 100]. */
    score?: number | null;
    /** Sedentary MET minutes. */
    sedentary_met_minutes: number;
    /** Sedentary time in seconds. */
    sedentary_time: number;
    /** Total number of steps taken. */
    steps: number;
    /** Daily activity target in kilocalories. */
    target_calories: number;
    /** Daily activity target in meters. */
    target_meters: number;
    /** Timestamp of the daily activity. */
    timestamp: LocalizedDateTime;
    /** Total calories expended in kilocalories. */
    total_calories: number;
}

/**
 * Daily Cardiovascular Age.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_cardiovascular_age
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age
 *  - GET /v2/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age/{document_id}
 */
export interface PublicDailyCardiovascularAge {
    /** Unique identifier of the object. */
    id: string;
    /** Meta data of the object. */
    meta: Metadata;
    /** Day that the prediction belongs to. */
    day: ISODate;
    /** Predicted vascular age in range [18, 100]. */
    vascular_age?: number | null;
}

/**
 * Public object defining daily readiness.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/daily_readiness/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_readiness/{document_id}
 */
export interface PublicDailyReadiness {
    /** Unique identifier of the object. */
    id: string;
    /** Meta data of the object. */
    meta: Metadata;
    /** Contributors of the daily readiness score. */
    contributors: PublicReadinessContributors;
    /** Day that the daily readiness belongs to. */
    day: ISODate;
    /** Daily readiness score. */
    score?: number | null;
    /** Temperature deviation in degrees Celcius. */
    temperature_deviation?: number | null;
    /** Temperature trend deviation in degrees Celcius. */
    temperature_trend_deviation?: number | null;
    /** Timestamp of the daily readiness. */
    timestamp: LocalizedDateTime;
}

/**
 * Public object defining daily sleep.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_sleep/{document_id}
 */
export interface PublicDailySleep {
    /** Unique identifier of the object. */
    id: string;
    /** Meta data of the object. */
    meta: Metadata;
    /** Contributors for the daily sleep score. */
    contributors: PublicSleepContributors;
    /** Day that the daily sleep belongs to. */
    day: ISODate;
    /** Daily sleep score. */
    score?: number | null;
    /** Timestamp of the daily sleep. */
    timestamp: LocalizedDateTime;
}

/**
 * Daily SpO2 (Oxygen saturation).
 *
 * Used by:
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 *  - GET /v2/usercollection/daily_spo2/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_spo2/{document_id}
 */
export interface PublicDailySpO2 {
    /** Unique identifier of the object. */
    id: string;
    /** Meta data of the object. */
    meta: Metadata;
    /** Breathing Disturbance Index (BDI) calculated using detected SpO2 drops from timeseries. Values should be in range [0, 100] */
    breathing_disturbance_index?: number | null;
    /** Day that the spo2 values belong to. */
    day: ISODate;
    /** The daily SpO2 percentage value aggregates. Sourced from SpO2 percentage timeseries values. */
    spo2_percentage?: PublicSpo2AggregatedValues | null;
}

/**
 * Daily stress.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 *  - GET /v2/usercollection/daily_stress/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_stress/{document_id}
 */
export interface PublicDailyStress {
    /** Unique identifier of the object. */
    id: string;
    /** Meta data of the object. */
    meta: Metadata;
    /** Day that the daily stress belongs to. */
    day: ISODate;
    /** Stress summary of full day. */
    day_summary?: PublicDailyStressSummary | null;
    /** Time spent in a high recovery zone (bottom quartile data) in seconds. */
    recovery_high?: number | null;
    /** Time spent in a high stress zone (top quartile of data) in seconds. */
    stress_high?: number | null;
}

/**
 * Possible public daily stress summary types.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 *  - GET /v2/usercollection/daily_stress/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_stress/{document_id}
 */
export type PublicDailyStressSummary = "restored" | "normal" | "stressful";

/**
 * Heart rate sample
 *
 * Used by:
 *  - GET /v2/usercollection/heartrate
 *  - GET /v2/sandbox/usercollection/heartrate
 */
export interface PublicHeartRateRow {
    /** Timestamp of the discrete sample. */
    timestamp: UtcDateTime;
    /** Timestamp of the discrete sample as unix time in milliseconds. */
    timestamp_unix: number;
    /** Heart rate as beats per minute. */
    bpm: number;
    /** Source of the sample. */
    source: PublicHeartRateSource;
}

/**
 * Possible heart rate sources.
 *
 * Used by:
 *  - GET /v2/usercollection/heartrate
 *  - GET /v2/sandbox/usercollection/heartrate
 */
export type PublicHeartRateSource = "awake" | "workout" | "rest" | "sleep" | "live" | "session";

/**
 * Discrete interbeat interval
 *
 * Used by:
 *  - GET /v2/usercollection/interbeat_interval
 *  - GET /v2/sandbox/usercollection/interbeat_interval
 */
export interface PublicInterbeatIntervalRow {
    /** Timestamp of the discrete sample. */
    timestamp: UtcDateTime;
    /** Timestamp of the discrete sample as unix time in milliseconds. */
    timestamp_unix: number;
    /** Time between two consecutive beats of the heart, in milliseconds. Maximum value limited to 2000ms. */
    ibi: number;
    /**
     * Validation classification: 1=Good,2=Bad,3=Corrected,-1/-2=Gap, 0=Raw(Uncorrected). The validity indicates
     * whether the data in this row is trustworthy. Gap: indicates that there was no available ppg signal in the
     * past seconds, which makes it impossible to compute the IBI for this row. Corrected: In rare cases the ring
     * algorithm produces artifacts that can be corrected during post-processing. An example is the ring algo
     * generating two IBI events when there should be a single one. If the IBI value was fixed in post-processing,
     * it will have this validity classification. If the IBI value was not fixed, it will have the Raw classification.
     */
    validity: number;
}

/**
 * PublicModifiedSleepModel
 *
 * Used by:
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export interface PublicModifiedSleepModel {
    /** Unique identifier of the object. */
    id: string;
    /** Meta data of the object. */
    meta: Metadata;
    /** Average breathing rate during sleep as breaths/minute. */
    average_breath?: number | null;
    /** Average heart rate during sleep as beats/minute. NOTE: this is the average calculated by ecore (based on 30-second samples) which is different from what is shown in the app. The app shows the average of aggregated 5-minute heart rate samples. */
    average_heart_rate?: number | null;
    /** Average heart rate variability during sleep. */
    average_hrv?: number | null;
    /** Duration spent awake in seconds. */
    awake_time?: number | null;
    /** Bedtime end of the sleep. */
    bedtime_end: LocalizedDateTime;
    /** Bedtime start of the sleep. */
    bedtime_start: LocalizedDateTime;
    /** Day that the sleep belongs to. */
    day: ISODate;
    /** Duration spent in deep sleep in seconds. */
    deep_sleep_duration?: number | null;
    /** Sleep efficiency rating in range [1, 100]. */
    efficiency?: number | null;
    /** Object containing heart rate samples. */
    heart_rate?: PublicSample | null;
    /** Object containing heart rate variability samples. */
    hrv?: PublicSample | null;
    /** Sleep latency in seconds. This is the time it took for the user to fall asleep after going to bed. */
    latency?: number | null;
    /** Duration spent in light sleep in seconds. */
    light_sleep_duration?: number | null;
    /** Flag indicating if a low battery alert occurred. */
    low_battery_alert: boolean;
    /** Lowest heart rate during sleep. NOTE: this is the value calculated by ecore (based on 30-second samples) which is different from what is shown in the app. The app shows the minimum of aggregated 5-minute heart rate samples. */
    lowest_heart_rate?: number | null;
    /**
     * 30-second movement classification for the period where every character corresponds to:
     * '1' = no motion,
     * '2' = restless,
     * '3' = tossing and turning
     * '4' = active
     * Example: "1143222134".
     */
    movement_30_sec?: string | null;
    /** ECore sleep period identifier. */
    period: number;
    /** Object containing the readiness details. */
    readiness?: PublicReadiness | null;
    /** Effect on readiness score caused by this sleep period. */
    readiness_score_delta?: number | null;
    /** Duration spent in REM sleep in seconds. */
    rem_sleep_duration?: number | null;
    /** Number of restless periods during sleep. */
    restless_periods?: number | null;
    /** Version of the sleep algorithm used to calculate the sleep data. */
    sleep_algorithm_version?: PublicSleepAlgorithmVersion | null;
    /** The reason for the creation or update of the latest version of this sleep. */
    sleep_analysis_reason?: PublicSleepAnalysisReason | null;
    /**
     * 30-second sleep phase classification for the period where every character corresponds to:
     * '1' = deep sleep,
     * '2' = light sleep,
     * '3' = REM sleep
     * '4' = awake.
     * Example: "444423323441114".
     */
    sleep_phase_30_sec?: string | null;
    /**
     * 5-minute sleep phase classification for the period where every character corresponds to:
     * '1' = deep sleep,
     * '2' = light sleep,
     * '3' = REM sleep
     * '4' = awake.
     * Example: "444423323441114".
     */
    sleep_phase_5_min?: string | null;
    /** Effect on sleep score caused by this sleep period. */
    sleep_score_delta?: number | null;
    /** Duration spent in bed in seconds. */
    time_in_bed: number;
    /** Total sleep duration in seconds. */
    total_sleep_duration?: number | null;
    /** Type of the sleep period. */
    type?: PublicSleepType | null;
    /** Encrypted identifier of the ring that produced this sleep data. */
    ring_id?: string | null;
    /**
     *         5-minute sleep phase classification for the period aligned with what is shown in the app
     *         where every character corresponds to:
     *         '1' = deep sleep,
     *         '2' = light sleep,
     *         '3' = REM sleep
     *         '4' = awake.
     *         Example: "444423323441114".
     *         NOTE: This field will be removed in the future after a transition period.
     */
    app_sleep_phase_5_min?: string | null;
}

/**
 * Possible Moment moods.
 *
 * Used by:
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 */
export type PublicMomentMood = "bad" | "worse" | "same" | "good" | "great";

/**
 * Possible Moment types.
 *
 * Used by:
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 */
export type PublicMomentType = "breathing" | "meditation" | "nap" | "relaxation" | "rest" | "body_status";

/**
 * Object defining readiness.
 *
 * Used by:
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export interface PublicReadiness {
    /** Contributors of the readiness score. */
    contributors: PublicReadinessContributors;
    /** Readiness score in range [1, 100]. */
    score?: number | null;
    /** Temperature deviation in degrees Celcius. */
    temperature_deviation?: number | null;
    /** Temperature trend deviation in degrees Celcius. */
    temperature_trend_deviation?: number | null;
}

/**
 * Object defining readiness score contributors.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/daily_readiness/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_readiness/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export interface PublicReadinessContributors {
    /** Contribution of cumulative activity balance in range [1, 100]. */
    activity_balance?: number | null;
    /** Contribution of body temperature in range [1, 100]. */
    body_temperature?: number | null;
    /** Contribution of heart rate variability balance in range [1, 100]. */
    hrv_balance?: number | null;
    /** Contribution of previous day's activity in range [1, 100]. */
    previous_day_activity?: number | null;
    /** Contribution of previous night's sleep in range [1, 100]. */
    previous_night?: number | null;
    /** Contribution of recovery index in range [1, 100]. */
    recovery_index?: number | null;
    /** Contribution of resting heart rate in range [1, 100]. */
    resting_heart_rate?: number | null;
    /** Contribution of sleep balance in range [1, 100]. */
    sleep_balance?: number | null;
    /** Contribution of sleep regularity in range [1, 100]. */
    sleep_regularity?: number | null;
}

/**
 * Object defining a public Rest Mode episode.
 *
 * Used by:
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 */
export interface PublicRestModeEpisode {
    /** Tags selected for the episode. */
    tags: string[];
    /** Timestamp indicating when the episode occurred. */
    timestamp: LocalizedDateTime;
}

/**
 * Rest mode episode information.
 *
 * Used by:
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 */
export interface PublicRestModePeriod {
    /** Unique identifier of the object. */
    id: string;
    /** Meta data of the object. */
    meta: Metadata;
    /** End date of rest mode. */
    end_day?: ISODate | null;
    /** Timestamp when rest mode ended. */
    end_time?: LocalizedDateTime | null;
    /** Collection of episodes during rest mode, consisting of tags. */
    episodes: PublicRestModeEpisode[];
    /** Start date of rest mode. */
    start_day: ISODate;
    /** Timestamp when rest mode ended. */
    start_time?: LocalizedDateTime | null;
}

/**
 * Object defining a ring battery level event.
 *
 * Used by:
 *  - GET /v2/usercollection/ring_battery_level
 *  - GET /v2/sandbox/usercollection/ring_battery_level
 */
export interface PublicRingBatteryLevelRow {
    /** Timestamp of the discrete sample. */
    timestamp: UtcDateTime;
    /** Timestamp of the discrete sample as unix time in milliseconds. */
    timestamp_unix: number;
    /** Flag indicating if the ring was charging. */
    charging?: boolean | null;
    /** Flag indicating if the ring was in charger. */
    in_charger?: boolean | null;
    /** Ring battery level percentage. These values are within [0, 100]. */
    level: number;
}

/**
 * Possible ring colors.
 *
 * Used by:
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 */
export type PublicRingColor =
    | "brushed_silver"
    | "glossy_black"
    | "glossy_gold"
    | "glossy_white"
    | "gucci"
    | "matt_gold"
    | "rose"
    | "silver"
    | "stealth_black"
    | "titanium"
    | "titanium_and_gold"
    | "cloud"
    | "petal"
    | "midnight"
    | "tide";

/**
 * Ring configuration.
 *
 * Used by:
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 */
export interface PublicRingConfiguration {
    /** Unique identifier of the object. */
    id: string;
    /** Meta data of the object. */
    meta: Metadata;
    /** Color of the ring. */
    color?: PublicRingColor | null;
    /** Design of the ring. */
    design?: PublicRingDesign | null;
    /** Firmware version of the ring. */
    firmware_version?: string | null;
    /** Hardware type of the ring. */
    hardware_type?: PublicRingHardwareType | null;
    /** UTC timestamp indicating when the ring was set up. */
    set_up_at?: UtcDateTime | null;
    /** US size of the ring. */
    size?: number | null;
}

/**
 * Possible ring designs.
 *
 * Used by:
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 */
export type PublicRingDesign = "heritage" | "balance" | "balance_diamond" | "horizon" | "ceramic";

/**
 * Possible ring hardware types.
 *
 * Used by:
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 */
export type PublicRingHardwareType = "gen1" | "gen2" | "gen2m" | "gen3" | "gen4";

/**
 * Object defining a recorded sample.
 *
 * Used by:
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export interface PublicSample {
    /** Interval in seconds between the sampled items. */
    interval: number;
    /** Recorded sample items. */
    items: ArrayUnionFloat_NoneType_Bits64_;
    /** Timestamp when the sample recording started. */
    timestamp: LocalizedDateTime;
}

/**
 * Public model defining a recorded Session.
 *
 * Used by:
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 */
export interface PublicSession {
    /** Unique identifier of the object. */
    id: string;
    /** Meta data of the object. */
    meta: Metadata;
    /** The date when the session occurred. */
    day: ISODate;
    /** Timestamp indicating when the Moment ended. */
    end_datetime: LocalizedDateTime;
    /** Recorded heart rate samples during the Moment. */
    heart_rate?: PublicSample | null;
    /** Recorded heart rate variability samples during the Moment. */
    heart_rate_variability?: PublicSample | null;
    /** User-selected mood for the Moment. */
    mood?: PublicMomentMood | null;
    /** Recorded motion count samples during the Moment. */
    motion_count?: PublicSample | null;
    /** Timestamp indicating when the Moment ended. */
    start_datetime: LocalizedDateTime;
    /** Type of the Moment. */
    type: PublicMomentType;
}

/**
 * Oura Sleep Staging Algorithms.
 * v1 = original aka legacy aka OSSA 1.0,
 * v2 = latest sleep algorithm
 *
 * Used by:
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export type PublicSleepAlgorithmVersion = "v1" | "v2";

/**
 * Possible sleep analysis reasons.
 *
 * Used by:
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export type PublicSleepAnalysisReason = "foreground_sleep_analysis" | "bedtime_edit";

/**
 * Object defining sleep score contributors.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_sleep/{document_id}
 */
export interface PublicSleepContributors {
    /** Contribution of deep sleep in range [1, 100]. */
    deep_sleep?: number | null;
    /** Contribution of sleep efficiency in range [1, 100]. */
    efficiency?: number | null;
    /** Contribution of sleep latency in range [1, 100]. */
    latency?: number | null;
    /** Contribution of REM sleep in range [1, 100]. */
    rem_sleep?: number | null;
    /** Contribution of sleep restfulness in range [1, 100]. */
    restfulness?: number | null;
    /** Contribution of sleep timing in range [1, 100]. */
    timing?: number | null;
    /** Contribution of total sleep in range [1, 100]. */
    total_sleep?: number | null;
}

/**
 * Suggested bedtime for the user.
 *
 * Used by:
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 */
export interface PublicSleepTime {
    /** Unique identifier of the object. */
    id: string;
    /** Meta data of the object. */
    meta: Metadata;
    /** Corresponding day for the sleep time. */
    day: ISODate;
    /** Optimal bedtime. */
    optimal_bedtime?: PublicSleepTimeWindow | null;
    /** Recommended action for bedtime. */
    recommendation?: PublicSleepTimeRecommendation | null;
    /** Sleep time status; used to inform sleep time recommendation. */
    status?: PublicSleepTimeStatus | null;
}

/**
 * Possible public SleepTime recommendation.
 *
 * Used by:
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 */
export type PublicSleepTimeRecommendation =
    | "improve_efficiency"
    | "earlier_bedtime"
    | "later_bedtime"
    | "earlier_wake_up_time"
    | "later_wake_up_time"
    | "follow_optimal_bedtime";

/**
 * Possible public SleepTime status.
 *
 * Used by:
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 */
export type PublicSleepTimeStatus =
    | "not_enough_nights"
    | "not_enough_recent_nights"
    | "bad_sleep_quality"
    | "only_recommended_found"
    | "optimal_found";

/**
 * Object defining sleep time window
 *
 * Used by:
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 */
export interface PublicSleepTimeWindow {
    /** Timezone offset in second from GMT of the day */
    day_tz: number;
    /** End offset from midnight in second */
    end_offset: number;
    /** Start offset from midnight in second */
    start_offset: number;
}

/**
 * Possible sleep period types.
 * 'deleted' = deleted sleep by user.
 * 'sleep' = user confirmed sleep / nap, min 15 minutes, max 3 hours, contributes to daily scores
 * 'late_nap' = user confirmed sleep / nap, min 15 minutes, ended after sleep day change (6 pm), contributes to next days daily scores
 * 'long_sleep' = sleep that is long enough (>3h) to automatically contribute to daily scores
 * 'rest' = Falsely detected sleep / nap, rejected in confirm prompt by user
 *
 * Used by:
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 */
export type PublicSleepType = "deleted" | "sleep" | "long_sleep" | "late_nap" | "rest";

/**
 * Object defining public spo2 aggregated values.
 *
 * Used by:
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 *  - GET /v2/usercollection/daily_spo2/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_spo2/{document_id}
 */
export interface PublicSpo2AggregatedValues {
    /** Average of spo2. */
    average: number;
}

/**
 * VO2Max estimate.
 *
 * Used by:
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 *  - GET /v2/usercollection/vO2_max/{document_id}
 *  - GET /v2/sandbox/usercollection/vO2_max/{document_id}
 */
export interface PublicVO2Max {
    /** Unique identifier of the object. */
    id: string;
    /** Meta data of the object. */
    meta: Metadata;
    /** Day that the estimate belongs to. */
    day: ISODate;
    /** Timestamp indicating when the estimate was created. */
    timestamp: LocalizedDateTime;
    /** VO2 max value. */
    vo2_max: number;
}

/**
 * Public model for Workout.
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 */
export interface PublicWorkout {
    /** Unique identifier of the object. */
    id: string;
    /** Meta data of the object. */
    meta: Metadata;
    /** Type of the workout activity. */
    activity: string;
    /** Energy burned in kilocalories during the workout. */
    calories?: number | null;
    /** Day when the workout occurred. */
    day: ISODate;
    /** Distance traveled in meters during the workout. */
    distance?: number | null;
    /** Timestamp indicating when the workout ended. */
    end_datetime: LocalizedDateTime;
    /** Intensity of the workout. */
    intensity: PublicWorkoutIntensity;
    /** User-defined label for the workout. */
    label?: string | null;
    /** Possible workout sources. */
    source: PublicWorkoutSource;
    /** Timestamp indicating when the workout started. */
    start_datetime: LocalizedDateTime;
}

/**
 * Possible workout intensities.
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 */
export type PublicWorkoutIntensity = "easy" | "moderate" | "hard";

/**
 * Possible workout sources.
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 */
export type PublicWorkoutSource = "manual" | "autodetected" | "confirmed" | "workout_heart_rate";

/**
 * ResilienceContributors
 *
 * Used by:
 *  - GET /v2/usercollection/daily_resilience
 *  - GET /v2/sandbox/usercollection/daily_resilience
 *  - GET /v2/usercollection/daily_resilience/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_resilience/{document_id}
 */
export interface ResilienceContributors {
    /** Sleep recovery contributor to the resilience score. Range: [0, 100] */
    sleep_recovery: number;
    /** Daytime recovery contributor to the resilience score. Range: [0, 100] */
    daytime_recovery: number;
    /** Stress contributor to the resilience score. Range: [0, 100] */
    stress: number;
}

/**
 * A TagModel maps to an ASSANote. An ASSANote in ExtAPIV2 is called a Tag
 * A TagModel will be populated by data from an ASSANote
 * The fields in the TagModel map to fields in an ASSANote
 *
 * Used by:
 *  - GET /v2/usercollection/tag
 *  - GET /v2/sandbox/usercollection/tag
 *  - GET /v2/usercollection/tag/{document_id}
 *  - GET /v2/sandbox/usercollection/tag/{document_id}
 */
export interface TagModel {
    /** Id */
    id: string;
    /**
     * Day that the note belongs to.
     *
     * Format: date
     */
    day: string;
    /** Textual contents of the note. */
    text: string | null;
    /** Timestamp of the note. */
    timestamp: LocalDateTime;
    /** Selected tags for the tag. */
    tags: string[];
}

/**
 * TimeSeriesResponseDict
 *
 * Used by:
 *  - GET /v2/usercollection/heartrate
 *  - GET /v2/sandbox/usercollection/heartrate
 *  - GET /v2/usercollection/ring_battery_level
 *  - GET /v2/sandbox/usercollection/ring_battery_level
 *  - GET /v2/usercollection/interbeat_interval
 *  - GET /v2/sandbox/usercollection/interbeat_interval
 */
export interface TimeSeriesResponseDict {
    /** Data */
    data: object[];
    /** Next Token */
    next_token?: string | null;
}

/**
 * TimeSeriesResponse[PublicHeartRateRow]
 *
 * Used by:
 *  - GET /v2/usercollection/heartrate
 *  - GET /v2/sandbox/usercollection/heartrate
 */
export interface TimeSeriesResponsePublicHeartRateRow_ {
    /** Data */
    data: PublicHeartRateRow[];
    /** Next Token */
    next_token?: string | null;
}

/**
 * TimeSeriesResponse[PublicInterbeatIntervalRow]
 *
 * Used by:
 *  - GET /v2/usercollection/interbeat_interval
 *  - GET /v2/sandbox/usercollection/interbeat_interval
 */
export interface TimeSeriesResponsePublicInterbeatIntervalRow_ {
    /** Data */
    data: PublicInterbeatIntervalRow[];
    /** Next Token */
    next_token?: string | null;
}

/**
 * TimeSeriesResponse[PublicRingBatteryLevelRow]
 *
 * Used by:
 *  - GET /v2/usercollection/ring_battery_level
 *  - GET /v2/sandbox/usercollection/ring_battery_level
 */
export interface TimeSeriesResponsePublicRingBatteryLevelRow_ {
    /** Data */
    data: PublicRingBatteryLevelRow[];
    /** Next Token */
    next_token?: string | null;
}

/**
 * UpdateWebhookSubscriptionRequest
 *
 * Used by:
 *  - PUT /v2/webhook/subscription/{id}
 */
export interface UpdateWebhookSubscriptionRequest {
    /** Verification Token */
    verification_token: string;
    /** Callback Url */
    callback_url?: string | null;
    event_type?: WebhookOperation | null;
    data_type?: ExtApiV2DataType | null;
}

/**
 * UtcDateTime
 *
 * Used by:
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 *  - GET /v2/usercollection/daily_cardiovascular_age
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 *  - GET /v2/usercollection/daily_sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_sleep/{document_id}
 *  - GET /v2/usercollection/daily_spo2/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_spo2/{document_id}
 *  - GET /v2/usercollection/daily_readiness/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_readiness/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 *  - GET /v2/usercollection/daily_stress/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_stress/{document_id}
 *  - GET /v2/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/usercollection/vO2_max/{document_id}
 *  - GET /v2/sandbox/usercollection/vO2_max/{document_id}
 *  - GET /v2/usercollection/heartrate
 *  - GET /v2/sandbox/usercollection/heartrate
 *  - GET /v2/usercollection/ring_battery_level
 *  - GET /v2/sandbox/usercollection/ring_battery_level
 *  - GET /v2/usercollection/interbeat_interval
 *  - GET /v2/sandbox/usercollection/interbeat_interval
 */
export type UtcDateTime = string;

/**
 * ValidationError
 *
 * Used by:
 *  - GET /v2/usercollection/tag
 *  - GET /v2/sandbox/usercollection/tag
 *  - GET /v2/usercollection/enhanced_tag
 *  - GET /v2/sandbox/usercollection/enhanced_tag
 *  - GET /v2/usercollection/workout
 *  - GET /v2/sandbox/usercollection/workout
 *  - GET /v2/usercollection/session
 *  - GET /v2/sandbox/usercollection/session
 *  - GET /v2/usercollection/daily_activity
 *  - GET /v2/sandbox/usercollection/daily_activity
 *  - GET /v2/usercollection/daily_sleep
 *  - GET /v2/sandbox/usercollection/daily_sleep
 *  - GET /v2/usercollection/daily_spo2
 *  - GET /v2/sandbox/usercollection/daily_spo2
 *  - GET /v2/usercollection/daily_readiness
 *  - GET /v2/sandbox/usercollection/daily_readiness
 *  - GET /v2/usercollection/sleep
 *  - GET /v2/sandbox/usercollection/sleep
 *  - GET /v2/usercollection/sleep_time
 *  - GET /v2/sandbox/usercollection/sleep_time
 *  - GET /v2/usercollection/rest_mode_period
 *  - GET /v2/sandbox/usercollection/rest_mode_period
 *  - GET /v2/usercollection/ring_configuration
 *  - GET /v2/sandbox/usercollection/ring_configuration
 *  - GET /v2/usercollection/daily_stress
 *  - GET /v2/sandbox/usercollection/daily_stress
 *  - GET /v2/usercollection/daily_resilience
 *  - GET /v2/sandbox/usercollection/daily_resilience
 *  - GET /v2/usercollection/daily_cardiovascular_age
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age
 *  - GET /v2/usercollection/vO2_max
 *  - GET /v2/sandbox/usercollection/vO2_max
 *  - GET /v2/usercollection/tag/{document_id}
 *  - GET /v2/sandbox/usercollection/tag/{document_id}
 *  - GET /v2/usercollection/enhanced_tag/{document_id}
 *  - GET /v2/sandbox/usercollection/enhanced_tag/{document_id}
 *  - GET /v2/usercollection/workout/{document_id}
 *  - GET /v2/sandbox/usercollection/workout/{document_id}
 *  - GET /v2/usercollection/session/{document_id}
 *  - GET /v2/sandbox/usercollection/session/{document_id}
 *  - GET /v2/usercollection/daily_activity/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_activity/{document_id}
 *  - GET /v2/usercollection/daily_sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_sleep/{document_id}
 *  - GET /v2/usercollection/daily_spo2/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_spo2/{document_id}
 *  - GET /v2/usercollection/daily_readiness/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_readiness/{document_id}
 *  - GET /v2/usercollection/sleep/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep/{document_id}
 *  - GET /v2/usercollection/sleep_time/{document_id}
 *  - GET /v2/sandbox/usercollection/sleep_time/{document_id}
 *  - GET /v2/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/sandbox/usercollection/rest_mode_period/{document_id}
 *  - GET /v2/usercollection/ring_configuration/{document_id}
 *  - GET /v2/sandbox/usercollection/ring_configuration/{document_id}
 *  - GET /v2/usercollection/daily_stress/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_stress/{document_id}
 *  - GET /v2/usercollection/daily_resilience/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_resilience/{document_id}
 *  - GET /v2/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/sandbox/usercollection/daily_cardiovascular_age/{document_id}
 *  - GET /v2/usercollection/vO2_max/{document_id}
 *  - GET /v2/sandbox/usercollection/vO2_max/{document_id}
 *  - POST /v2/webhook/subscription
 *  - GET /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/{id}
 *  - DELETE /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/renew/{id}
 *  - GET /v2/usercollection/heartrate
 *  - GET /v2/sandbox/usercollection/heartrate
 *  - GET /v2/usercollection/ring_battery_level
 *  - GET /v2/sandbox/usercollection/ring_battery_level
 *  - GET /v2/usercollection/interbeat_interval
 *  - GET /v2/sandbox/usercollection/interbeat_interval
 */
export interface ValidationError {
    /** Location */
    loc: string | number[];
    /** Message */
    msg: string;
    /** Error Type */
    type: string;
}

/**
 * WebhookOperation
 *
 * Used by:
 *  - GET /v2/webhook/subscription
 *  - POST /v2/webhook/subscription
 *  - GET /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/renew/{id}
 */
export type WebhookOperation = "create" | "update" | "delete";

/**
 * WebhookSubscriptionModel
 *
 * Used by:
 *  - GET /v2/webhook/subscription
 *  - POST /v2/webhook/subscription
 *  - GET /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/{id}
 *  - PUT /v2/webhook/subscription/renew/{id}
 */
export interface WebhookSubscriptionModel {
    /**
     * Id
     *
     * Format: uuid4
     */
    id: string;
    /** Callback Url */
    callback_url: string;
    /** WebhookOperation */
    event_type: WebhookOperation;
    /** ExtApiV2DataType */
    data_type: ExtApiV2DataType;
    /**
     * Expiration Time
     *
     * Format: date-time
     */
    expiration_time: string;
}
