# .github/workflows/publish-jsr.yml

name: Publish to JSR

on:
  create:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write 
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish --config jsr.json